#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  devbox:
    image: node:12.16.3-alpine3.11
    ports:
      - 3000:3000

    tmpfs:
      - /workspace/node_modules:exec
      - /workspace/examples/node_modules:exec
    
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:consistent

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
